- name: Get the name of the service instance
  shell: oc get serviceinstance --namespace={{ namespace }} -o jsonpath='{.items[?(@.spec.externalID=="{{ _apb_service_instance_id }}")].metadata.name}'
  when: _apb_service_instance_id is defined
  register: service_instance_name

- name: Label the service instance with the service name
  shell: oc label serviceinstance '{{ service_instance_name.stdout }}' serviceName=unifiedpush --namespace={{ namespace }}
  when: _apb_service_instance_id is defined

- name: "Create OAuth Proxy Serviceaccount yaml"
  template:
    src: oauth-proxy-sa.yml.j2
    dest: /tmp/oauth-proxy-sa.yaml

- name: "Create OAuth Proxy Serviceaccount"
  shell: "oc create -f /tmp/oauth-proxy-sa.yaml -n {{ namespace }}"

- name: "Delete OAuth proxy Template File"
  file: path=/tmp/oauth-proxy-sa.yaml state=absent

- name: Give default user admin permissions
  shell: 'oc policy add-role-to-user admin system:serviceaccount:{{ namespace }}:{{ proxy_serviceaccount_name }} -n {{ namespace }}'

- include_tasks: provision-database.yml 
- include_tasks: provision-ups.yml
