- name: Get the name of the service instance
  shell: oc get serviceinstance --namespace={{ namespace }} -o jsonpath='{.items[?(@.spec.externalID=="{{ _apb_service_instance_id }}")].metadata.name}'
  when: _apb_service_instance_id is defined
  register: service_instance_name

- name: Label the service instance with the service name
  shell: oc label serviceinstance '{{ service_instance_name.stdout }}' serviceName=unifiedpush --namespace={{ namespace }}
  when: _apb_service_instance_id is defined

- name: MySQL PVC
  k8s_v1_persistent_volume_claim:
    name: mysql
    namespace: "{{ namespace }}"
    labels:
      app: mysql
      service: mysql
    access_modes:
      - ReadWriteOnce
    resources_requests:
      storage: 10Gi
    state: present

- name: MySQL deployment
  openshift_v1_deployment_config:
    name: mysql
    namespace: "{{ namespace }}"
    labels:
      app: mysql
      service: mysql
    replicas: 1
    selector:
      app: mysql
      service: mysql
    spec_template_metadata_labels:
      app: mysql
      service: mysql
    containers:
    - name: mysql
      image: docker.io/openshift/mysql-{{ MYSQL_VERSION }}-centos7
      env:
      - name: MYSQL_USER
        value: "{{ MYSQL_USER }}"
      - name: MYSQL_PASSWORD
        value: "{{ MYSQL_PASSWORD }}"
      - name: MYSQL_ROOT_PASSWORD
        value: "{{ MYSQL_ROOT_PASSWORD }}"
      - name: MYSQL_DATABASE
        value: "{{ MYSQL_DATABASE }}"
      ports:
      - name: mysql
        protocol: TCP
        container_port: 3306
      liveness_probe:
        timeout_seconds: 1
        inital_delay_seconds: 30
        tcp_socket:
          port: 3306
      readiness_probe:
        timeout_seconds: 1
        initial_delay_seconds: 5
        _exec:
          command:
          - "/bin/sh"
          - "-i"
          - "-c"
          - "MYSQL_PWD=\"$MYSQL_PASSWORD\" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE -e 'SELECT 1'"
      volume_mounts:
      - mount_path: /var/lib/mysql/data
        name: mysql-data
    volumes:
    - name: mysql-data
      persistent_volume_claim:
        claim_name: mysql
    triggers:
    - type: ConfigChange
    state: present

- name: MySQL service
  k8s_v1_service:
    name: mysql
    namespace: "{{ namespace }}"
    labels:
      app: mysql
      service: mysql
    selector:
      app: mysql
      service: mysql
    ports:
    - name: mysql
      port: 3306
      target_port: 3306
    state: present
  register: mysql_service

- name: "Create OAuth Proxy Serviceaccount yaml"
  template:
    src: oauth-proxy-sa.yml.j2
    dest: /tmp/oauth-proxy-sa.yaml

- name: "Create OAuth Proxy Serviceaccount"
  shell: "oc create -f /tmp/oauth-proxy-sa.yaml -n {{ namespace }}"

- name: "Delete OAuth proxy Template File"
  file: path=/tmp/oauth-proxy-sa.yaml state=absent

# Check the containers in the mysql pod and make sure they are all ready
- name: "Wait for all mysql containers to become ready"
  shell: oc get pods --namespace={{ namespace }} --selector="deploymentconfig=mysql" -o jsonpath='{.items[*].status.containerStatuses[?(@.ready==true)].ready}'| wc -w
  register: mysql_result
  until: mysql_result.stdout.find("1") != -1
  retries: 30
  delay: 5

- name: UPS deployment
  openshift_v1_deployment_config:
    name: ups
    namespace: "{{ namespace }}"
    labels:
      app: ups
      service: ups
      name: ups
      mobile: enabled
    replicas: 1
    selector:
      app: ups
      service: ups
    spec_template_metadata_labels:
      app: ups
      service: ups
    spec_template_spec_service_account_name: '{{ proxy_serviceaccount_name }}'
    containers:
    - name: ups
      image: '{{ ups_image }}:{{ ups_image_tag }}'
      env:
      - name: MYSQL_USER
        value: "{{ MYSQL_USER }}"
      - name: MYSQL_PASSWORD
        value: "{{ MYSQL_PASSWORD }}"
      - name: MYSQL_DATABASE
        value: "{{ MYSQL_DATABASE }}"
      ports:
      - name: ups
        protocol: TCP
        container_port: 8080
    - name: ups-oauth-proxy
      image: '{{ proxy_image }}:{{ proxy_image_tag }}'
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: '{{ ups_proxy_port }}'
        name: public
      args:
      - --provider=openshift
      - --openshift-service-account={{ proxy_serviceaccount_name }}
      - --upstream=http://localhost:{{ ups_port }}
      - >-
        --openshift-sar={"namespace":"{{ namespace }}","resource":"deploymentconfigs","name":"ups","verb":"update"}
      - --http-address=0.0.0.0:{{ ups_proxy_port }}
      - --https-address=
      - --cookie-secret=SECRET

- name: create UPS service
  k8s_v1_service:
    name: ups
    namespace: '{{ namespace }}'
    annotations:
      org.aerogear.metrics/plain_endpoint: "/ag-push/rest/prometheus/metrics"
    labels:
      app: ups
      service: ups
      mobile: enabled
    selector:
      app: ups
      service: ups
    ports:
      - name: web
        port: 80
        target_port: 8080

- name: create UPS Proxy
  k8s_v1_service:
    name: ups-proxy
    namespace: '{{ namespace }}'
    labels:
      app: ups
      service: ups-proxy
    selector:
      app: ups
      service: ups
    ports:
      - name: web
        port: 80
        target_port: '{{ ups_proxy_port }}'

- name: create ups route
  openshift_v1_route:
    name: ups
    namespace: '{{ namespace }}'
    labels:
      app: ups
      service: ups-proxy
    to_name: ups-proxy
    spec_port_target_port: web
    spec_tls_termination: edge

- name: "Retrieve route to ups-server"
  shell: "oc get routes ups -n {{ namespace }} | grep -v NAME | awk '{print $2}'"
  register: ups_route

- name: "Create ups secret yaml file"
  template:
    src: secret.yml.j2
    dest: /tmp/secret.yaml

- name: "Create UPS secret"
  shell: "oc create -f /tmp/secret.yaml -n {{ namespace }}"

- name: "Delete UPS Secret Template File"
  file: path=/tmp/secret.yaml state=absent

# We need to wait for the deployment to be ready before we can exit the ansible job
- name: "Wait for all UPS containers to become ready"
  shell: oc get pods --namespace={{ namespace }} --selector="deploymentconfig=ups" -o jsonpath='{.items[*].status.containerStatuses[?(@.ready==true)].ready}'| wc -w
  register: ups_result
  until: ups_result.stdout.find("2") != -1
  retries: 30
  delay: 5