- name: unifiedpush-apb playbook to bind the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
  - /opt/ansible/vars/main.yml
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: bind-unifiedpush-apb
    playbook_debug: false